### ISSUE TITLE
для кого это блять?..

### ISSUE THREAD

**Issue by ikibastus1** [VDFOREVER/ArchOptimization#1]
пиздец...

**Comment by VDFOREVER** [comment]
Я написал себе скрипт который ставит мне не обходимые программы и драйвера

**Comment by ikibastus1** [comment]
> Я написал себе скрипт который ставит мне не обходимые программы и драйвера

так зачем ты его выложил тогда?

**Comment by VDFOREVER** [comment]
Чтобы не потерять и кидать этот скрипт тем кому помогаю arch настраивать
